config/routes.rb
Rails.application.routes.draw do
  resources :messages, except: %i[ index show ] do
    post 'retweet', to: 'messages#retweet'
  end

  get  'login',  to: 'sessions#new'
  get  'logout', to: 'sessions#destroy'
  post 'login',  to: 'sessions#create'

  get  'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  root 'timeline#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  validates :text, presence: { message: 'or Image must be informed!' }, if: -> { image.blank? }

  attr_accessor :image

  before_save   :save_image
  after_destroy :destroy_image

  def save_image
    return if self.image.blank?
    
    file_name = SecureRandom.uuid + File.extname(self.image.original_filename)
    file_url  = File.join('/uploads', file_name)
    file_path = File.join(Rails.root, 'public', file_url)

    File.open(file_path, 'wb') do |file|
      file.write(self.image.read)
    end

    self.image_url = file_url
  end

  def destroy_image
    return if self.image_url.blank?

    file_path = File.join(Rails.root, 'public', self.image_url)

    File.delete(file_path) if File.exist?(file_path)
  end

  def retweet
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_secure_password

  validates :name, :email, presence: true
  validates :email,        uniqueness: { case_sensitive: false }

  def authenticate(password)
    user = super(password)

    return user if user.is_a?(User)

    errors.add(:password, 'is invalid!')

    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  helper_method :current_user


  private 
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session.present?
  end

  def authorize
   # session[:redirect_to] = request.url
    redirect_to login_path, alert: 'You must login for creating new messages!' if current_user.nil?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only:   %i[edit update destroy]
  before_action :permission?, except: %i[new create retweet]
  before_action :authorize

  # GET /messages/new
  def new
    redirect_to root_path
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  def create
    @message = Message.new(message_params)

    if @message.save
      redirect_to root_path, notice: "Message was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /messages/1
  def update
    if @message.update(message_params)
      redirect_to root_path, notice: "Message was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /messages/1
  def destroy
    @message.destroy
    redirect_to root_path, notice: "Message was successfully destroyed.", status: :see_other
  end

  def retweet
    message = Message.find(params[:message_id])
    message.retweet
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:user_id, :text, :image).merge(user_id: current_user.id)
    end
    def permission?
      redirect_to logout_path unless current_user == @message.user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    session[:redirect_to] = nil
    @user = User.new
  end

  def create
    @user = User.find_by(email: session_params[:email]) || User.new

    if @user.present? && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to (session.delete(:redirect_to) || root_path)
    else
      # redirect_to login_path, alert: 'Email or password is invalid!'
      render :new, status: :unauthorized
    end
  end

  def destroy
    session[:user_id] = nil
    @current_user     = nil

    redirect_to login_path, notice: 'Logged out'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  def index
    @message  = Message.new
    @pagy, @messages = pagy(Message.order(created_at: :desc))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Welcome #{@user.name}!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to 'Home', root_path %>
      <% if current_user.present? %>
        <%= link_to 'Logout', logout_path %>
        <p>You're logged as <%= current_user.name  %></p>
      <% else %>
        <%= link_to 'Login', login_path %>
        <%= link_to 'Sign up', signup_path %>
      <% end %>
    </nav>

    <% flash.each do |type, msg| %>
      <div class="type "><%= msg %></div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
  <% if message.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
        <% message.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :text, style: "display: block" %>
    <%= form.text_field :text %>
  </div>

  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/_list.html.erb
<div id="messages">
  <br>
  <%== pagy_nav(@pagy) %>

  <% @messages.each do |message| %>
    <%= render message %>
  <% end %>

  <%== pagy_nav(@pagy) %>
</div>

app/views/messages/_message.html.erb
<div style="border: 1px solid black" id='<%= dom_id message %>'>
  <p>
    <strong>User:</strong>
    <%= message.user.name %>
  </p>

  <% if message.text.present? %>
    <p>
      <strong>Text:</strong>
      <%= message.text %>
    </p>
  <% end %>

  <% if message.image_url.present? %>
    <p>
      <strong>Image url:</strong>
      <%= image_tag message.image_url, width: 100 %>
    </p>
  <% end %>

  <p>
    <% if current_user.present? && current_user.id == message.user_id %>
      <%= link_to "Edit this message", edit_message_path(message) %> |
      <%= link_to "Destroy this message", message, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% else %>
      <%= link_to "Retweet this message", message_retweet_path(message), data: { turbo_method: :post } %>
    <% end %>
  </p>

</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "form", message: @message %>

<br>

<div>
  <%= link_to "Back to timeline", root_path %>
</div>

app/views/timeline/index.html.erb
<% if current_user.present? %>
    <%= render 'messages/form', message: @message %>
<% else %>
    <%= link_to "New message", new_message_path %>
<% end %>

<%= render 'messages/list' %>

app/views/users/new.html.erb
<h1>Create your account</h1>

<%= form_for :user do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div>
    <%= form.label :name %>
    <div>
      <%= form.text_field :name %> 
    </div> 
  </div>
  <div>
    <%= form.label :email %>
    <div>
      <%= form.email_field :email %> 
    </div> 
  </div>
  <div>
    <%= form.label :password %>
    <div>
      <%= form.password_field :password %> 
    </div> 
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>